name: Sorting Automation Test

on:
  push:
    branches:
      - ft/pipeline
  pull_request:
    branches:
      - ft/pipeline

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Playwright dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          libgtk-4-1 libgraphene-1.0-0 libevent-2.1-7 libopus0 \
          gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-libav \
          libflite1 libavif16 libharfbuzz-icu0 libwayland-server0 libmanette-0.2-0 \
          libhyphen0 libsecret-1-0 libwoff1 libgles2 libx264-163

      - name: Install dependencies
        run: mvn install -DskipTests
        working-directory: SortingFunctionalityAutomation

      - name: Run tests
        run: mvn test
        working-directory: SortingFunctionalityAutomation
