name: CI CD Pipeline

on:
  push:
    branches: [ main, dev, ft/pipeline ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
steps:
  name: Checkout code
  uses: actions/checkout@v4

      # 2️⃣ Setup Java
      
  name: Set up JDK 21
  uses: actions/setup-java@v4
  with:
    java-version: '21'
    distribution: 'microsoft'
    cache: maven
      
  name: Install dependencies
  run: mvn clean install -DskipTests
      
  name: Install Playwright Browsers
  run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"
      
  name: Run Automated Tests
  run: mvn test
